Repository AY2122S1-CS2113T-T09-4/tp, pull requests merged in 2021-10, with the labels that each got.

#28 Extracted calendar command with exceptions
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commands/DisplayCalendarCommand.java
  src/main/java/seedu/duke/constants/CommandConstants.java
  src/main/java/seedu/duke/constants/Messages.java
  src/main/java/seedu/duke/exceptions/InvalidArgumentsException.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/parser/schedule/ParserSchedule.java
  src/main/java/seedu/duke/schedule/Schedule.java
  src/main/java/seedu/duke/ui/Ui.java
  src/main/java/seedu/duke/ui/schedule/UiSchedule.java
  src/test/java/seedu/duke/parser/ParserTest.java
  src/test/java/seedu/duke/parser/schedule/ParserScheduleTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Story

#76 Branch module exception
  src/main/java/seedu/duke/commands/AddModuleCommand.java
  src/main/java/seedu/duke/commands/DeleteModuleCommand.java
  src/main/java/seedu/duke/commands/ListModuleCommand.java
  src/main/java/seedu/duke/exceptions/IllegalModuleException.java
  src/main/java/seedu/duke/exceptions/IllegalModuleIndexException.java
  src/main/java/seedu/duke/module/Module.java
  src/main/java/seedu/duke/module/ModuleList.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/storage/StorageModule.java
Labels: priority.Medium, type.Enhancement

#95 updated dg content
  docs/DeveloperGuide.md
  docs/images/CalendarDisplaySequence.puml
  docs/images/calendar_body.png
  docs/images/calendar_header.png
  docs/team/DG_swati.md
  src/main/java/seedu/duke/schedule/Calendar.puml
Labels: type.Task

#113 DG edit journal
  docs/team/DG_svetha.md
Labels: priority.High

#123 editing UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High, type.Task

#226 Branch nigel code review v2.0
  docs/UserGuide.md
  src/main/java/seedu/duke/commands/HelpCommand.java
  src/main/java/seedu/duke/commands/food/AddFoodCommand.java
  src/main/java/seedu/duke/commands/food/FindFoodWithDateCommand.java
  src/main/java/seedu/duke/commands/food/ViewReferenceFoodCommand.java
  src/main/java/seedu/duke/commands/module/DeleteModuleCommand.java
  src/main/java/seedu/duke/constants/CommandConstants.java
  src/main/java/seedu/duke/food/ReferenceLists.java
  src/main/java/seedu/duke/food/WhatIAteList.java
  src/main/java/seedu/duke/foodreferencelists/StallsManager.java
Labels: type.Task, bug.documentation
