Repository AY2122S1-CS2113T-T09-4/tp, pull requests merged in 2021-11, with the labels that each got.

#227 Branch exception handler
  docs/UserGuide.md
  src/main/java/seedu/duke/commands/module/AddModuleCommand.java
  src/main/java/seedu/duke/constants/ExceptionMessages.java
  src/main/java/seedu/duke/exceptions/ClickException.java
  src/main/java/seedu/duke/exceptions/ExceptionHandler.java
  src/main/java/seedu/duke/exceptions/IllegalCommandException.java
  src/main/java/seedu/duke/exceptions/StorageException.java
  src/main/java/seedu/duke/exceptions/food/FoodIndexNotFoundException.java
  src/main/java/seedu/duke/exceptions/food/IllegalFoodParameterException.java
  src/main/java/seedu/duke/exceptions/food/MissingDateException.java
  src/main/java/seedu/duke/exceptions/module/IllegalCurrentCapException.java
  src/main/java/seedu/duke/exceptions/module/IllegalExpectedGradeException.java
  src/main/java/seedu/duke/exceptions/module/IllegalModularCreditException.java
  src/main/java/seedu/duke/exceptions/module/IllegalModuleException.java
  src/main/java/seedu/duke/exceptions/module/IllegalModuleIndexException.java
  src/main/java/seedu/duke/exceptions/module/IllegalTotalMcTakenException.java
  src/main/java/seedu/duke/module/ModuleManager.java
  src/main/java/seedu/duke/parser/Parser.java
Labels: priority.Medium, type.Enhancement

#228 Branch module enhancement
  src/main/java/seedu/duke/commands/module/AddModuleCommand.java
  src/main/java/seedu/duke/constants/ExceptionMessages.java
  src/main/java/seedu/duke/exceptions/module/DuplicateModuleException.java
  src/main/java/seedu/duke/exceptions/module/IllegalCurrentCapException.java
  src/main/java/seedu/duke/exceptions/module/IllegalExpectedGradeException.java
  src/main/java/seedu/duke/exceptions/module/IllegalModularCreditException.java
  src/main/java/seedu/duke/exceptions/module/IllegalModuleException.java
  src/main/java/seedu/duke/exceptions/module/IllegalModuleIndexException.java
  src/main/java/seedu/duke/exceptions/module/IllegalTotalMcTakenException.java
  src/main/java/seedu/duke/module/ModuleList.java
  src/main/java/seedu/duke/module/ModuleManager.java
  src/test/java/seedu/duke/module/GradePointsTest.java
  src/test/java/seedu/duke/module/ModuleListTest.java
  src/test/java/seedu/duke/module/ModuleManagerTest.java
Labels: priority.Medium, type.Enhancement, severity.Medium

#229 Branch nigel exceptions
  src/main/java/seedu/duke/commands/food/AddFoodCommand.java
  src/main/java/seedu/duke/commands/food/AddFoodFromReferenceCommand.java
  src/main/java/seedu/duke/constants/Messages.java
  src/main/java/seedu/duke/exceptions/ArgumentsNotFoundException.java
  src/main/java/seedu/duke/exceptions/ExceptionHandler.java
  src/main/java/seedu/duke/exceptions/food/FoodCaloriesNotFoundException.java
  src/main/java/seedu/duke/exceptions/food/FoodIndexNotFoundException.java
  src/main/java/seedu/duke/exceptions/food/FoodNameNotFoundException.java
  src/main/java/seedu/duke/exceptions/food/IllegalFoodParameterException.java
  src/main/java/seedu/duke/exceptions/food/MissingDateException.java
  src/main/java/seedu/duke/parser/Parser.java
  src/test/java/seedu/duke/food/FoodTest.java
Labels: type.Task

#231 Add community section to the PPP
  docs/team/nvbinh15.md
Labels: priority.Low

#232 ppp draft svetha
  docs/team/svethamahadevan.md
Labels: priority.High, type.Task

#234 Add food clt command, update user guide and help command
  docs/UserGuide.md
  src/main/java/seedu/duke/commands/HelpCommand.java
  src/main/java/seedu/duke/commands/food/AddFoodCommand.java
  src/main/java/seedu/duke/commands/food/AddFoodFromReferenceCommand.java
  src/main/java/seedu/duke/commands/food/DeleteFoodCommand.java
  src/main/java/seedu/duke/commands/food/FindFoodByCalorieCount.java
  src/main/java/seedu/duke/commands/food/FindFoodWithDateCommand.java
  src/main/java/seedu/duke/commands/food/ViewReferenceFoodCommand.java
  src/main/java/seedu/duke/commands/zoom/AddZoomCommand.java
  src/main/java/seedu/duke/constants/CommandConstants.java
  src/main/java/seedu/duke/constants/Messages.java
  src/main/java/seedu/duke/exceptions/ArgumentsNotFoundException.java
  src/main/java/seedu/duke/exceptions/ExceptionHandler.java
  src/main/java/seedu/duke/exceptions/FileNotFoundException.java
  src/main/java/seedu/duke/exceptions/InvalidArgumentsException.java
  src/main/java/seedu/duke/exceptions/WrongDividerOrderException.java
  src/main/java/seedu/duke/exceptions/food/CannotFindFoodStoreException.java
  src/main/java/seedu/duke/exceptions/food/InvalidItemIndexException.java
  src/main/java/seedu/duke/exceptions/food/InvalidStoreIndexException.java
  src/main/java/seedu/duke/exceptions/food/NegativeCaloriesException.java
  src/main/java/seedu/duke/exceptions/food/NoCalorieCountKeywordException.java
  src/main/java/seedu/duke/exceptions/food/NoCaloriesInputException.java
  src/main/java/seedu/duke/exceptions/food/NoFoodFoundOnDateException.java
  src/main/java/seedu/duke/exceptions/food/NoItemDividerException.java
  src/main/java/seedu/duke/exceptions/food/NoStoreDividerException.java
  src/main/java/seedu/duke/exceptions/storage/FileNotFoundException.java
  src/main/java/seedu/duke/exceptions/storage/StorageException.java
  src/main/java/seedu/duke/exceptions/syntax/ArgumentsNotFoundException.java
  src/main/java/seedu/duke/exceptions/syntax/HelpException.java
  src/main/java/seedu/duke/exceptions/syntax/IllegalCommandException.java
  src/main/java/seedu/duke/exceptions/syntax/IllegalDateTimeException.java
  src/main/java/seedu/duke/exceptions/syntax/InvalidArgumentsException.java
  src/main/java/seedu/duke/exceptions/syntax/MissingDividerException.java
  src/main/java/seedu/duke/exceptions/syntax/WrongDividerOrderException.java
  src/main/java/seedu/duke/food/FoodRecord.java
  src/main/java/seedu/duke/food/WhatIAteList.java
  src/main/java/seedu/duke/foodreferencelists/StallsManager.java
  src/main/java/seedu/duke/help/ClassPackageReader.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/parser/module/ParserModule.java
  src/main/java/seedu/duke/storage/StorageModule.java
  src/main/java/seedu/duke/storage/StorageZoom.java
  src/test/java/seedu/duke/food/FoodTest.java
  src/test/java/seedu/duke/parser/ParserTest.java
  src/test/java/seedu/duke/parser/module/ParserModuleTest.java
Labels: priority.High, type.Story, bug.documentation

#238 Branch fix module bug
  docs/UserGuide.md
  src/main/java/seedu/duke/Click.java
  src/main/java/seedu/duke/commands/module/AddModuleCommand.java
  src/main/java/seedu/duke/commands/module/ListModuleCommand.java
  src/main/java/seedu/duke/constants/CommandConstants.java
  src/main/java/seedu/duke/constants/ExceptionMessages.java
  src/main/java/seedu/duke/exceptions/ExceptionHandler.java
  src/main/java/seedu/duke/exceptions/module/DuplicateModuleParamException.java
  src/main/java/seedu/duke/exceptions/module/IllegalModularCreditException.java
  src/main/java/seedu/duke/exceptions/module/IllegalModuleCommandException.java
  src/main/java/seedu/duke/exceptions/module/StorageModuleException.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/parser/module/ParserModule.java
  src/main/java/seedu/duke/storage/StorageModule.java
  src/test/java/seedu/duke/parser/module/ParserModuleTest.java
Labels: priority.Medium

#237 fixed ped bugs and minor changes
  src/main/java/seedu/duke/commands/calendar/AddLectureCommand.java
  src/main/java/seedu/duke/commands/calendar/AddTodoCommand.java
  src/main/java/seedu/duke/commands/calendar/EditTasksCommand.java
  src/main/java/seedu/duke/exceptions/calendar/LectureIncorrectDateException.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/parser/schedule/ParserSchedule.java
  src/main/java/seedu/duke/schedule/Schedule.java
Labels: type.Task, type.Bug

#240 Bug fixes
  docs/UserGuide.md
  src/main/java/seedu/duke/commands/journal/AddEntryCommand.java
  src/main/java/seedu/duke/commands/journal/AddNoteCommand.java
  src/main/java/seedu/duke/commands/journal/DeleteEntryCommand.java
  src/main/java/seedu/duke/commands/journal/DeleteNoteCommand.java
  src/main/java/seedu/duke/commands/journal/FindNotebooksByTagCommand.java
  src/main/java/seedu/duke/commands/journal/TagNotebookCommand.java
  src/main/java/seedu/duke/exceptions/journal/DuplicateNoteException.java
  src/main/java/seedu/duke/exceptions/journal/EmptyDeleteNoteException.java
  src/main/java/seedu/duke/exceptions/journal/EmptyEntryArgumentsException.java
  src/main/java/seedu/duke/exceptions/journal/EmptyEntryNameException.java
  src/main/java/seedu/duke/exceptions/journal/EmptyFindTagException.java
  src/main/java/seedu/duke/exceptions/journal/EmptyJournalArgumentException.java
  src/main/java/seedu/duke/exceptions/journal/EmptyNoteArgumentsException.java
  src/main/java/seedu/duke/exceptions/journal/EmptyNoteNameException.java
  src/main/java/seedu/duke/exceptions/journal/EmptyTagArgumentsException.java
  src/main/java/seedu/duke/exceptions/journal/EmptyTagNameException.java
  src/main/java/seedu/duke/exceptions/journal/EntryDoesNotExistException.java
  src/main/java/seedu/duke/exceptions/journal/IncorrectJournalArgumentException.java
  src/main/java/seedu/duke/exceptions/journal/InvalidAddEntryArgumentException.java
  src/main/java/seedu/duke/exceptions/journal/InvalidAddTagArgumentException.java
  src/main/java/seedu/duke/exceptions/journal/InvalidDeleteEntryArgumentException.java
  src/main/java/seedu/duke/exceptions/journal/InvalidDeleteNoteArgumentException.java
  src/main/java/seedu/duke/exceptions/journal/InvalidEntryIndexException.java
  src/main/java/seedu/duke/exceptions/journal/InvalidNotebookIndexException.java
  src/main/java/seedu/duke/exceptions/journal/InvalidTagNameException.java
  src/main/java/seedu/duke/exceptions/journal/NotebookArgumentNotFoundException.java
  src/main/java/seedu/duke/exceptions/journal/NotebookNotFoundForEntry.java
  src/main/java/seedu/duke/exceptions/journal/NotebookNotFoundForTagException.java
  src/main/java/seedu/duke/parser/journal/ParserJournal.java
  src/test/java/seedu/duke/parser/journal/ParserJournalTest.java
Labels: type.Bug, severity.Medium

#239 Move all data file to 1 directory
  .gitignore
  src/main/java/seedu/duke/storage/StorageEntries.java
  src/main/java/seedu/duke/storage/StorageFood.java
  src/main/java/seedu/duke/storage/StorageLecture.java
  src/main/java/seedu/duke/storage/StorageModule.java
  src/main/java/seedu/duke/storage/StorageNotes.java
  src/main/java/seedu/duke/storage/StorageTasks.java
  src/main/java/seedu/duke/storage/StorageZoom.java
Labels: priority.Medium, type.Enhancement, severity.Medium

#243 Branch nigel ppp
  docs/team/ngnigel99.md
Labels: bug.documentation

#248 Branch binh dg
  docs/DeveloperGuide.md
Labels: priority.Medium, bug.documentation

#252 fixed aboutus link
  docs/AboutUs.md
Labels: type.Bug

#256 dg-additions
  docs/DeveloperGuide.md
  src/test/java/seedu/duke/parser/journal/ParserJournalTest.java
Labels: priority.Medium, type.Task

#258 PPP_Svetha added
  docs/team/svethamahadevan.md
Labels: priority.High

#259 minor fixes journal
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/commands/journal/AddEntryCommand.java
  src/main/java/seedu/duke/commands/journal/DeleteEntryCommand.java
  src/main/java/seedu/duke/commands/journal/TagNotebookCommand.java
  src/main/java/seedu/duke/exceptions/journal/EmptyNoteIndexException.java
  src/main/java/seedu/duke/exceptions/journal/NotebookNotFoundForEntry.java
  src/main/java/seedu/duke/journal/Note.java
  src/main/java/seedu/duke/parser/journal/ParserJournal.java
Labels: priority.Low

#261 Branch fix module bug
  src/main/java/seedu/duke/Click.java
  src/main/java/seedu/duke/commands/module/AddModuleCommand.java
  src/main/java/seedu/duke/commands/module/CapEditInfoCommand.java
  src/main/java/seedu/duke/commands/module/GetExpectedCapCommand.java
  src/main/java/seedu/duke/constants/ExceptionMessages.java
  src/main/java/seedu/duke/constants/Messages.java
  src/main/java/seedu/duke/constants/ModuleConstants.java
  src/main/java/seedu/duke/exceptions/ExceptionHandler.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/parser/module/ParserModule.java
  src/main/java/seedu/duke/storage/StorageModule.java
Labels: priority.Low, type.Enhancement, bug.documentation

#262 Update DG ToC, add module model design
  docs/DeveloperGuide.md
  docs/images/module/Module.png
  docs/images/module/Module.puml
  docs/team/DG_binh.md
Labels: bug.documentation

#267 Add error handling for food-related file manipulation
  src/main/java/seedu/duke/storage/StorageFood.java
Labels: type.Task, type.Bug, bug.documentation

#266 Branch nigel dg edit
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/ClickRun.png
  docs/images/ClickRun.puml
  docs/images/food/FoodClassDiagram.puml
  docs/images/food/Parser_getFoodCommand.puml
  docs/images/food/Style.puml
  docs/images/food/foodClassDiagram.png
  docs/images/food/food_architecture.png
  docs/images/help/HelpCommand_execute-Help_Commands.png
  docs/images/help/HelpCommand_execute.puml
  docs/images/help/Style.puml
  docs/images/help/helpCommandsClassDiagram.png
  docs/images/help/helpCommandsClassDiagram.puml
  src/main/java/seedu/duke/foodreferencelists/StallsManager.java
Labels: bug.documentation

#273 remove spaces in dg
  docs/DeveloperGuide.md
Labels: priority.Medium

#275 Branch fix module bug
  src/main/java/seedu/duke/exceptions/zoom/InvalidZoomDataPath.java
  src/main/java/seedu/duke/module/ModuleManager.java
  src/main/java/seedu/duke/storage/StorageModule.java
  src/main/java/seedu/duke/storage/StorageZoom.java
Labels: priority.Medium, type.Enhancement, severity.Medium

#270 Removed whitespace from command syntax
  src/main/java/seedu/duke/commands/food/AddFoodCommand.java
  src/main/java/seedu/duke/commands/food/AddFoodFromReferenceCommand.java
  src/main/java/seedu/duke/constants/CommandConstants.java
Labels: bug.documentation

#276 Branch exception message
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/food/Parser_getFoodCommand.puml
  docs/diagrams/food/food_architecture.png
  docs/diagrams/help/HelpCommand_execute-Help_Commands.png
  docs/diagrams/help/Style.puml
  docs/team/DG_nigel.md
  docs/team/ngnigel99.md
  src/main/java/seedu/duke/commands/food/AddFoodFromReferenceCommand.java
  src/main/java/seedu/duke/commands/food/ViewReferenceFoodCommand.java
  src/main/java/seedu/duke/exceptions/food/IllegalFoodCommandException.java
  src/main/java/seedu/duke/foodreferencelists/StallsManager.java
  src/main/java/seedu/duke/parser/Parser.java
Labels: type.Enhancement, type.Task, bug.documentation

#281 Fix help message string
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/calendar/CalendarDisplaySequence.png
  docs/diagrams/calendar/CalendarDisplaySequence.puml
  docs/diagrams/calendar/DeleteTaskCommand.png
  docs/diagrams/calendar/DeleteTaskCommand.puml
  docs/diagrams/journal/AddNoteCommand.png
  docs/diagrams/journal/AddNoteCommand.puml
  docs/diagrams/journal/DeleteNoteCommand.png
  docs/diagrams/journal/DeleteNoteCommand.puml
  docs/diagrams/module/AddModule.png
  docs/diagrams/module/AddModule.puml
  docs/diagrams/module/ListModule.png
  docs/diagrams/module/ListModule.puml
  src/main/java/seedu/duke/constants/CommandConstants.java
Labels: bug.documentation

#294 User guide styling
  docs/UserGuide.md
Labels: bug.documentation
